name: Release crates
on:
  pull_request:
    types: closed
    branches: [main]

jobs:
  info:
    if: github.event.pull_request.merged
    outputs:
      is-release: ${{ steps.meta.outputs.is-release }}
      crate: ${{ steps.meta.outputs.crate-names }}
      version: ${{ steps.meta.outputs.version-actual }}
      notes: ${{ steps.meta.outputs.notes }}
    runs-on: ubuntu-latest
    steps:
    - id: meta
      uses: cargo-bins/release-meta@v1
      with:
        event-data: ${{ toJSON(github.event) }}
        extract-notes-under: '### Release notes'

  release:
    needs: info
    if: needs.info.outputs.is-release == 'true'
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/cargo@v1
      with:
        command: publish
        args: -p kafkaesque-macros --token ${{ secrets.CRATES_TOKEN }}
    - uses: actions-rs/cargo@v1
      with:
        command: publish
        args: -p kafkaesque --token ${{ secrets.CRATES_TOKEN }}

