name: Release crates

on:
  create:
    tags:
      - v*

jobs:
  publish:
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        crate: [kafkaesque-macros, kafkaesque]
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Test
      run: make test-ci
    - uses: actions-rs/cargo@v1
      with:
        command: publish
        args: -p ${{ matrix.crate }} --token ${{ secrets.CRATES_TOKEN }}
