name: Release crates
on:
  pull_request:
    types: closed
    branches: [main]

jobs:
  info:
    if: github.event.pull_request.merged
    outputs:
      is-release: ${{ steps.meta.outputs.is-release }}
      crate: ${{ steps.meta.outputs.crate-names }}
      version: ${{ steps.meta.outputs.version-actual }}
      notes: ${{ steps.meta.outputs.notes }}
    runs-on: ubuntu-latest
    steps:
    - id: meta
      uses: cargo-bins/release-meta@v1
      with:
        event-data: ${{ toJSON(github.event) }}
        extract-notes-under: '### Release notes'

  release:
    needs: info
    if: needs.info.outputs.is-release == 'true'
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cargo-bins/release-rust@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        publish-token: ${{ secrets.CRATES_TOKEN }}
        packaging: tar+zstd
        crates: ${{ needs.info.outputs.crate }}
        release-tag: v${{ needs.info.outputs.version }}
        release-notes: ${{ needs.info.outputs.notes }}
